name: Create Jira Release via Webhook

on:
  workflow_run:
    workflows: [Daily Release]
    types:
      - completed

permissions:
  contents: read  # Cho phép đọc thông tin release
jobs:
  send-jira-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Get latest tag and project name
        id: get_info
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "VERSION=$LATEST_TAG" >> $GITHUB_ENV
          echo "PROJECT_NAME=${{ github.repository }}" >> $GITHUB_ENV

      - name: Extract Jira issues and changelog content
        id: extract_data
        run: |
          if [ -f CHANGELOG.MD ]; then
            echo "Reading CHANGELOG.MD..."
            cat CHANGELOG.MD  # Debug nội dung file
            
            # Lấy danh sách Jira Key theo format như FC-2345
            ISSUES=$(grep -oE '[A-Z]{2,}-[0-9]+' CHANGELOG.MD | sort -u)
            
            if [ -z "$ISSUES" ]; then
              ISSUES="[]"  # Nếu không có issue nào, trả về mảng rỗng JSON
            else
              ISSUES=$(echo "$ISSUES" | jq -R -s -c 'split("\n")[:-1]')
            fi

            # Đọc toàn bộ nội dung CHANGELOG.MD và escape JSON
            CHANGELOG_CONTENT=$(jq -Rs '.' < CHANGELOG.MD)
          else
            echo "File CHANGELOG.MD not found!"
            ISSUES="[]"
            CHANGELOG_CONTENT="\"No changelog available\""
          fi
          
          echo "Extracted Jira Issues: $ISSUES"
          echo "ISSUES=$ISSUES" >> $GITHUB_ENV
          echo "CHANGELOG_CONTENT=$CHANGELOG_CONTENT" >> $GITHUB_ENV

      - name: Debug release info
        run: |
          echo "Release Version: $VERSION"
          echo "Project Name: $PROJECT_NAME"
          echo "Jira Issues: $ISSUES"
          echo "Changelog Content: $CHANGELOG_CONTENT"

      - name: Send Incoming Webhook to Jira
        run: |
          curl -X POST \
          -H "Content-type: application/json" \
          -H "X-Automation-Webhook-Token: ${{ secrets.JIRA_WEBHOOK_TOKEN }}" \
          --data '{
            "issues": '"${ISSUES}"',
            "data": {
              "releaseVersion": "'"${VERSION}"'",
              "projectName": "'"${PROJECT_NAME}"'",
              "changelog": '"${CHANGELOG_CONTENT}"'
            }
          }' \
          "${{ secrets.JIRA_WEBHOOK_URL }}"
